#!/bin/sh

set -eu

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [[ -d "$HOME/.oh-my-zsh" ]]; then
    echo "Oh My Zsh is already installed, skipping..."
  else
    echo "Oh My Zsh is not installed, proceeding with the installation..."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle install
  fi

  if [ ! -d "/Applications/iTerm.app" ]; then
    echo "Installing iTerm"
    brew install iterm2
  fi

  if [ -d "$HOME/.iterm2" ]; then
  echo "Setting iTerm preference folder"
  defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:rxrw/dotfiles.git"

# Install vim-plug for Vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +'PlugInstall --sync' +qa
# FIXME: How to bootstrap LazyNvim?
# # Install vim-plug for Neovim
# sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
#      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
# nvim +'PlugInstall --sync' +qa

echo "Decrypt secrets...."
yadm decrypt
